---
settings:
  name: ONTAP tools for VMware vSphere 10.2
  downlevel: true
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: it-it,us-en,de-de,es-es,fr-fr,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Tool ONTAP per documenti VMware vSphere 10,2
    url: "/index.html"
  - section: release-notes
  - section: concepts
  - section: deploy
  - section: configure
  - section: protect
  - section: manage
  - section: upgrade
  - section: recover
  - section: migrate
  - section: automation
  - title: Note legali
    url: "/legal-notices.html"
