---
permalink: concepts/autosupport.html 
sidebar: sidebar 
keywords:  
summary: 'AutoSupport è un meccanismo che monitora in modo proattivo lo stato di salute del sistema e invia automaticamente messaggi al supporto tecnico NetApp, all"organizzazione di supporto interna e a un partner di supporto.' 
---
= AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AutoSupport è un meccanismo che monitora in modo proattivo lo stato di salute del sistema e invia automaticamente messaggi al supporto tecnico NetApp, all'organizzazione di supporto interna e a un partner di supporto.

AutoSupport è attivato per impostazione predefinita quando si configura il sistema di storage per la prima volta. AutoSupport inizia a inviare messaggi al supporto tecnico 24 ore dopo l'attivazione di AutoSupport.

È possibile attivare o disattivare AutoSupport solo al momento della distribuzione. Si consiglia di lasciarlo attivato. L'attivazione di AutoSupport consente di velocizzare il rilevamento dei problemi e di ottenere una risoluzione più rapida. Il sistema raccoglie le informazioni AutoSupport e le memorizza localmente, anche quando AutoSupport è disattivato. Tuttavia, non invia il rapporto a nessuna rete. Per una trasmissione corretta, è necessario includere l'URL 216.240.21.18 // support.netapp.com nella rete.
