---
permalink: configure/configure-network-access.html 
sidebar: sidebar 
keywords:  
summary: 'È possibile scegliere di consentire pochi indirizzi host ESXi specifici per l"operazione di montaggio del datastore.' 
---
= Configurare l'accesso alla rete
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si dispone di più indirizzi IP dell'host ESXi, tutti gli indirizzi IP rilevati dall'host vengono aggiunti a un criterio di esportazione per impostazione predefinita. Se non si desidera aggiungere tutti gli indirizzi IP a un criterio di esportazione, fornire un'impostazione per consentire specifici indirizzi IP in un elenco o intervallo separati da virgola o CIDR o una combinazione di tutti e tre per ogni vCenter.

È possibile scegliere di consentire alcuni indirizzi host ESXi specifici per l'operazione di montaggio del datastore. Se l'impostazione non viene fornita, il criterio di esportazione aggiunge tutti gli indirizzi IP rilevati nella fase di pre-montaggio. Se viene fornita l'impostazione, gli strumenti ONTAP per VMware vSphere aggiungono solo quelli che rientrano nell'intervallo o negli indirizzi IP elencati. Se nessuno degli indirizzi IP di un host appartiene agli indirizzi IP elencati, il montaggio su tale host non riesce.

.Fasi
. Accedere al client vSphere utilizzando `\https://vcenterip/ui`
. Nella pagina dei collegamenti, fare clic su *NetApp ONTAP tools* nella sezione dei plug-in.
. Nel riquadro sinistro degli strumenti di ONTAP, selezionare *Impostazioni* > *Gestisci accesso alla rete* > *Modifica*.
+
Utilizzare una virgola (,) per separare gli indirizzi IP. È possibile specificare un indirizzo IP specifico, un intervallo di indirizzi IP o IPv6.

. Fare clic su *Save* (Salva).

