---
permalink: manage/expand-storage-of-vvol-datastore.html 
sidebar: sidebar 
keywords: virtual volume datastores 
summary: 'Quando si fa clic con il pulsante destro del mouse sull"oggetto del datastore nella vista oggetto vCenter, gli strumenti ONTAP per le azioni supportate da VMware vSphere sono visualizzati nella sezione del plug-in.' 
---
= Espandere vVol Datastore
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando si fa clic con il pulsante destro del mouse sull'oggetto del datastore nella vista oggetto vCenter, gli strumenti ONTAP per le azioni supportate da VMware vSphere sono visualizzati nella sezione del plug-in. Le azioni specifiche vengono attivate in base al tipo di datastore e ai privilegi dell'utente corrente.

*Fasi*

. Dalla home page del client vSphere, fare clic su *host e cluster*.
. Nel riquadro di navigazione, selezionare il data center che contiene il datastore.
. Fare clic con il pulsante destro del mouse sul datastore e selezionare *Strumenti NetApp ONTAP* > *Aggiungi storage al datastore*.
. Nella finestra *crea o Seleziona volumi*, è possibile creare nuovi volumi o scegliere tra quelli esistenti. L'interfaccia utente è autoesplicativa. Seguire le istruzioni a scelta.
. Nella finestra *Riepilogo*, rivedere le selezioni e fare clic su *Espandi*. È possibile tenere traccia dell'avanzamento nel pannello attività recenti.

