---
permalink: manage/remove-storage-from-a-vvols-datastore.html 
sidebar: sidebar 
keywords: Remove vVol datastore 
summary: 'L"azione Elimina archivio dati elimina il datastore quando non sono presenti vVol nel datastore selezionato.' 
---
= Restringere il datastore vVol
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'azione Elimina archivio dati elimina il datastore quando non sono presenti vVol nel datastore selezionato.

.Fasi
. Dalla home page del client vSphere, fare clic su *host e cluster*.
. Nel riquadro di navigazione, selezionare il data center che contiene il datastore.
. Fare clic con il pulsante destro del mouse sul datastore vVol e selezionare *NetApp ONTAP tools* > *Rimuovi archiviazione dal datastore*.
. Selezionare i volumi che non dispongono di vVol e fare clic su *Rimuovi*.
+

NOTE: L'opzione per selezionare il volume su cui risiedono i vVol è disattivata.

. Nella finestra pop-up *Rimuovi storage*, seleziona la casella di controllo *Elimina volumi dal cluster ONTAP* per eliminare i volumi dal datastore e dallo storage ONTAP e fai clic su *Elimina*.

