---
permalink: manage/resize-datastores.html 
sidebar: sidebar 
keywords:  
summary: 'Il ridimensionamento di un datastore consente di aumentare lo storage dei file delle macchine virtuali. È possibile modificare le dimensioni di un datastore in base al cambiamento dei requisiti dell"infrastruttura.' 
---
= Ridimensionare il datastore NFS e VMFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il ridimensionamento di un datastore consente di aumentare lo storage dei file delle macchine virtuali. È possibile modificare le dimensioni di un datastore in base al cambiamento dei requisiti dell'infrastruttura.

*A proposito di questa attività*

È possibile aumentare le dimensioni di un datastore NFS e VMFS. Un volume FlexVol che fa parte di un datastore NFS e VMFS non può ridursi al di sotto delle dimensioni esistenti, ma può crescere fino al 120%.

*Fasi*

. Dalla home page del client vSphere, fare clic su *host e cluster*.
. Nel riquadro di navigazione, selezionare il data center che contiene il datastore.
. Fare clic con il pulsante destro del mouse sul datastore NFS o VMFS e selezionare *NetApp ONTAP tools* > *Ridimensiona datastore*.
. Nella finestra di dialogo Ridimensiona, specificare una nuova dimensione per l'archivio dati e fare clic su *OK*.

